# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# source 'https://github.com/CocoaPods/Specs.git'

target 'RTCSolution' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   use_frameworks!

  # Pods for RTCSolution
pod 'RTCCommon', :path => 'RTCCommon/' 
pod 'RTCCommonView', :path => 'RTCCommonView/' 
pod 'RTCVoiceCall', :path => 'RTCVoiceCall/' 
pod 'RTCInteractiveLiveClass', :path => 'RTCInteractiveLiveClass/' 
pod 'RTCAudioLiveRoom', :path => 'RTCAudioLiveRoom/' 

pod 'AliRTCSdk'

 pod 'AFNetworking', '4.0.1'

#pod 'AliPlayerSDK_iOS', :git => 'https://github.com/aliyunvideo/AliPlayerSDK.git',:tag=>'4.7.4'

end
